# Generated by Django 3.0.8 on 2020-09-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicar',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
