# Generated by Django 3.0.8 on 2020-07-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('industria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('precio_apertura', models.FloatField()),
                ('precio_maximo', models.FloatField()),
                ('precio_minimo', models.FloatField()),
                ('precio_cierre', models.FloatField()),
                ('volumen', models.FloatField()),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('precio_apertura', models.FloatField()),
                ('precio_maximo', models.FloatField()),
                ('precio_minimo', models.FloatField()),
                ('precio_cierre', models.FloatField()),
                ('volumen', models.FloatField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Sector'),
        ),
    ]
